"""Add new health metrics

Revision ID: 9cd5f0f58d64
Revises: eb0757b7d037
Create Date: 2024-08-03 20:00:25.205141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd5f0f58d64'
down_revision = 'eb0757b7d037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respiratory_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hydration_level', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sleep_duration', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hours_since_feeding', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reading', schema=None) as batch_op:
        batch_op.drop_column('hours_since_feeding')
        batch_op.drop_column('sleep_duration')
        batch_op.drop_column('hydration_level')
        batch_op.drop_column('respiratory_rate')

    # ### end Alembic commands ###
